# # Numpy Crash Course

In [1]:
import numpy as np
print(np.__version__)

2.4.6


In [2]:
np.__version__

'2.4.6'

In [2]:
import sys
sys.version

'3.14.6 | packaged by Anaconda, Inc. | (main, Jul  9 2026, 14:29:05) [MSC v.1942 64 bit (AMD64)]'

# Creating LIST

In [5]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
type(my_list)

list

# below code we are converting list to array

In [3]:
#!pip install numpy

In [7]:
my_list = [0,1,2,3,4,5]

In [8]:
arr = np.array(my_list)

In [9]:
arr

array([0, 1, 2, 3, 4, 5])

In [10]:
type(arr)

numpy.ndarray

In [11]:
type(my_list)

list

In [ ]:
np.  # we learn important function

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [19]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [21]:
type(arr)

numpy.ndarray

In [22]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
np.arange(10,20,30)

array([10])

In [24]:
np.arange(20,10)

array([], dtype=int64)

In [25]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [26]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [27]:
np.arange(30,20)  # 1st arg always be < then 2nd arg

array([], dtype=int64)

In [28]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [29]:
np.arange(10,10)

array([], dtype=int64)

In [ ]:
np.arange()

In [31]:
np.arange(10,30,5)  # 10- starting from 30- end point 5 - step count

array([10, 15, 20, 25])

In [32]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [33]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

# Zeros Parameter Tunning

In [34]:
np.zeros(10) # parameter  tunning 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
np.zeros(5, dtype=int) # hyperparameter tunnin

array([0, 0, 0, 0, 0])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [7]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [13]:
np.zeros((2,3),dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
np.zeros((10,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [36]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunnin g

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


# Parameter

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [37]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [38]:
np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [42]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# Hyperparametrer

In [44]:
np.ones((6,10),dtype = int) 

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [45]:
range(5)

range(0, 5)

In [46]:
r = range(5)
r

range(0, 5)

In [47]:
for i in r:
    print(i)

0
1
2
3
4


In [48]:
list(range(5))

[0, 1, 2, 3, 4]

In [49]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

# Start Stop Step

In [51]:
list(range(1,10,3))

[1, 4, 7]

In [53]:
list(range(1,20,5))

[1, 6, 11, 16]

In [55]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

# random 

In [58]:
random.rand(3,2)

NameError: name 'random' is not defined

In [ ]:
# OPT Generator

In [17]:
random.rand(2)

NameError: name 'random' is not defined

In [18]:
np.random.rand(2)

array([0.63484161, 0.16543077])

In [19]:
np.random.rand(2,3) # only float value

array([[0.70428707, 0.45258921, 0.5467283 ],
       [0.03519819, 0.19583903, 0.04351164]])

In [20]:
np.random.randint(2) # it will generate integer value

1

In [21]:
np.random.randint(2,9)

2

In [22]:
np.random.randint(2,9)

6

In [23]:
np.random.randint(2,9)

2

In [24]:
np.random.randint(2,9)

6

In [25]:
np.random.randint(2,9)

5

In [29]:
np.random.randint(2,9,4) #generate random integer  2 to 9 and where 9 is exclude

array([5, 7, 6, 5], dtype=int32)

In [32]:
np.random.randint(10,40,(10,10))

array([[36, 32, 16, 23, 23, 20, 28, 20, 27, 29],
       [35, 29, 12, 28, 16, 22, 10, 15, 36, 29],
       [33, 12, 18, 19, 38, 38, 36, 21, 33, 15],
       [38, 22, 27, 29, 33, 24, 33, 26, 36, 11],
       [18, 30, 21, 33, 29, 31, 24, 19, 28, 26],
       [28, 10, 13, 26, 37, 30, 13, 21, 16, 21],
       [19, 36, 24, 24, 19, 28, 15, 13, 38, 27],
       [12, 22, 16, 27, 26, 27, 20, 11, 12, 12],
       [11, 33, 26, 12, 28, 28, 18, 10, 32, 35],
       [26, 22, 32, 19, 34, 37, 22, 13, 22, 33]], dtype=int32)

In [61]:
arr1 = np.random.randint(10,40,(10,10))
print(arr1)

[[25 17 25 31 11 12 24 31 14 31]
 [17 38 16 16 29 26 26 31 19 34]
 [15 38 11 17 25 28 23 35 18 33]
 [19 19 15 18 20 34 17 20 19 20]
 [15 11 32 18 25 27 34 28 15 20]
 [20 38 18 19 13 30 13 32 17 32]
 [33 29 35 28 21 36 31 34 34 24]
 [28 32 36 35 17 19 30 27 35 15]
 [33 30 27 33 26 22 10 29 37 37]
 [35 21 17 25 25 15 26 10 23 22]]


In [33]:
arr1[5]

array([11, 23, 16, 19, 16, 17, 13, 22, 29, 36], dtype=int32)

In [59]:
np.random.randint(1,100,(12,12))

array([[16, 42, 50, 13, 30, 74, 16, 18, 52,  7, 16, 77],
       [81, 25, 57, 73, 70, 59, 19, 89, 32, 42, 62, 55],
       [55, 49, 12, 66, 30, 13, 40, 37,  9,  7, 83, 64],
       [89, 64, 14, 33, 91, 55, 29, 43,  6, 74, 57, 54],
       [90, 22, 24, 16, 75, 56, 96, 12,  6, 17,  9, 81],
       [79, 63, 81, 21, 33, 61, 88, 80, 24, 13, 24, 38],
       [24, 76,  4, 49, 50, 31, 26,  2, 43, 53, 60, 28],
       [69, 41, 46, 20, 54, 89, 81, 89, 41, 59,  4, 69],
       [39, 45, 78, 62,  5, 19, 91, 59, 35, 75, 67, 85],
       [98, 85,  8, 63, 79, 89, 34, 97, 75, 12, 81, 26],
       [ 3, 70, 56, 40, 99,  3, 65,  9, 10, 95, 19, 76],
       [61, 20, 63, 79, 82, 34, 69, 46, 26, 10, 53, 39]], dtype=int32)

In [60]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [62]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [64]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [65]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

# Slicing in Matrix

In [66]:
b = np.random.randint(10,20,(5,4))
b

array([[11, 17, 15, 16],
       [11, 15, 15, 17],
       [12, 11, 11, 14],
       [14, 17, 10, 11],
       [14, 12, 18, 12]], dtype=int32)

In [67]:
type(b)

numpy.ndarray

In [68]:
b[:]

array([[11, 17, 15, 16],
       [11, 15, 15, 17],
       [12, 11, 11, 14],
       [14, 17, 10, 11],
       [14, 12, 18, 12]], dtype=int32)

In [69]:
b[:3]

array([[11, 17, 15, 16],
       [11, 15, 15, 17],
       [12, 11, 11, 14]], dtype=int32)

In [70]:
b[3:2]

array([], shape=(0, 4), dtype=int32)

In [71]:
b[1:3]

array([[11, 15, 15, 17],
       [12, 11, 11, 14]], dtype=int32)

In [72]:
b[1,2]

np.int32(15)

In [73]:
b

array([[11, 17, 15, 16],
       [11, 15, 15, 17],
       [12, 11, 11, 14],
       [14, 17, 10, 11],
       [14, 12, 18, 12]], dtype=int32)

In [74]:
b[3:2]

array([], shape=(0, 4), dtype=int32)

In [75]:
b[1,3]

np.int32(17)

In [76]:
b[1,-1]

np.int32(17)

# Operations

In [78]:
a = np.random.randint(10,20,10)
a

array([11, 15, 19, 12, 15, 10, 18, 15, 13, 10], dtype=int32)

In [79]:
id(a)

2732048527120

In [80]:
arr

array([0, 1, 2, 3, 4, 5])

In [83]:
arr2 = np.random.randint(0,100,(10,10))

In [84]:
arr2

array([[78, 71, 41,  2, 72, 32, 92, 98, 50, 51],
       [69, 59, 88, 86, 78,  5, 49, 29, 14, 80],
       [50, 96, 26, 92, 15, 95, 61, 93, 77, 86],
       [40, 63, 88, 72, 22, 97, 28, 12, 64,  4],
       [67, 71, 17, 47, 90, 42, 72, 26,  3,  7],
       [ 5, 74, 51, 45, 76, 34, 79, 21, 55, 80],
       [57, 93, 24, 17, 25,  8,  2, 86, 16, 68],
       [92, 75, 32, 17, 44,  6, 19, 44, 67, 19],
       [64, 28, 38, 39, 62, 90, 38, 54, 63, 98],
       [57, 75, 60, 81, 66, 26, 99, 69, 76,  5]], dtype=int32)

In [85]:
arr

array([0, 1, 2, 3, 4, 5])

In [86]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [87]:
arr2[:]

array([[78, 71, 41,  2, 72, 32, 92, 98, 50, 51],
       [69, 59, 88, 86, 78,  5, 49, 29, 14, 80],
       [50, 96, 26, 92, 15, 95, 61, 93, 77, 86],
       [40, 63, 88, 72, 22, 97, 28, 12, 64,  4],
       [67, 71, 17, 47, 90, 42, 72, 26,  3,  7],
       [ 5, 74, 51, 45, 76, 34, 79, 21, 55, 80],
       [57, 93, 24, 17, 25,  8,  2, 86, 16, 68],
       [92, 75, 32, 17, 44,  6, 19, 44, 67, 19],
       [64, 28, 38, 39, 62, 90, 38, 54, 63, 98],
       [57, 75, 60, 81, 66, 26, 99, 69, 76,  5]], dtype=int32)

In [88]:
arr2[-5:-5]

array([], shape=(0, 10), dtype=int32)

In [89]:
arr2[-1:-2]

array([], shape=(0, 10), dtype=int32)

In [90]:
arr.max()

np.int64(5)

In [91]:
arr2.max()

np.int32(99)

In [93]:
arr.min()

np.int64(0)

In [94]:
arr2.min()

np.int32(2)

In [96]:
arr2.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [97]:
from numpy import * # 256 function called internally
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

# # Without work on import* can you please find the median, mode)

In [98]:
arr

array([0, 1, 2, 3, 4, 5])

In [99]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [100]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [102]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [103]:
arr.reshape(6,2)

ValueError: cannot reshape array of size 6 into shape (6,2)

In [104]:
arr.reshape(3,2,order='C') 

array([[0, 1],
       [2, 3],
       [4, 5]])

In [105]:
arr.reshape(2,3,order='F') # print element with fortran

array([[0, 2, 4],
       [1, 3, 5]])

In [106]:
arr.reshape(2,3,order='A') # A almost give you c type output

array([[0, 1, 2],
       [3, 4, 5]])

In [107]:
# importing Numpy package 
import numpy as np

# creating a Numpy array
num_array = np.arange(100).reshape(20, 5)
print(num_array)

# Display array in Fortran order 

print("\n  C type array:")
for num_array in np.nditer(num_array, order="C"):
	print(num_array,end=' ')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]

  C type array:
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

In [108]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [4]:
import numpy as np

# Indexing

In [5]:
mat = np.arange(0,100).reshape(10,10) 
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [6]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [8]:
row = 4
col = 5

In [10]:
mat[row,col]

np.int64(45)

In [11]:
mat[4,5]

np.int64(45)

In [12]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [13]:
mat[7] # befault it represent to rows

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [15]:
# With Slices
mat[:,col] 
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [16]:
mat[:,col] 

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [17]:
mat[row,:] 

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [18]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

# Masking

In [19]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [20]:
id(mat)

1969498416464

In [21]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [22]:
mat[mat==50] 

array([50])

In [23]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [24]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [25]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [26]:
a3 = mat[mat<=50] 
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [27]:
a4 = mat[mat==50]
a4

array([50])


# Python Program to Generate OTP

In [28]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 1123


In [29]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 4451


In [30]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 2303
